# Testing libraries (nbval, flake8, and flake8-nb)
# are not considered dependencies. They are pip-installed
# separately on CI.

name: introduction-to-python

channels:
  - defaults

dependencies:
  - pip
  - python=3.9  # Python 3.9 also works, but we are being a bit conservative here.
  - pip:
    - jupytext
    - nbformat
    - nbconvert